paginate: 1
paginate_path: "/news/page:num/"

gems:
  - jekyll-feed

authors:
  scott:
    display_name: Scott
    gravatar: e9b1824da5b46f8f5000c8eada796eda
    github: sarostru
  dann:
    display_name: Dann
    gravatar:
    github: dxnn
  j0ni:
    display_name: J
    gravatar: e26838cd1064441fead19103f1af54d8
    github: j0ni

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
