paginate: 10
paginate_path: "/news/page:num/"

name: Toronto CSCabal
description: news and happenings of the Toronto CSCabal
url: http://compscicabal.github.io

plugins:
  - jekyll-feed
  - jekyll-paginate

authors:
  scott:
    display_name: Scott
    gravatar: e9b1824da5b46f8f5000c8eada796eda
    github: sarostru
  dann:
    display_name: Dann
    gravatar:
    github: dxnn
  j0ni:
    display_name: J
    gravatar: e26838cd1064441fead19103f1af54d8
    github: j0ni
  erik:
    display_name: Erik
    gravatar: aed06902677ef88a160e777a4ea200dcd114f6b7efc896482ca5667ba32737e6
    github: erik-j-d
  inaimathi:
    display_name: Inaimathi
    gravatar:
    github: inaimathi

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
